[package]
name = "aqua-registry"
version = "0.1.0"
edition = "2021"
description = "Aqua registry for mise"
authors = ["Jeff Dickey (@jdx)"]
license = "MIT"
repository = "https://github.com/jdx/mise"

[features]
baked = []

[dependencies]
eyre = "0.6"
indexmap = "2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
once_cell = "1"
strum = { version = "0.27", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
async-trait = "0.1"
itertools = "0.14"
regex = "1"
dashmap = "6"
semver = "1"
expr = { package = "expr-lang", version = "0.3" }
versions = "6"

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

[dev-dependencies]
tokio-test = "0.4"
